# Site settings
title: David Laprade | Blog
description: "A minimal blog template, build with Jekyll."
url: "http://davidlaprade.github.io/blog"
author:
  name: "David Laprade"
  email: "david.laprade@gmail.com"
  url: "http://davidlaprade.github.io"

# Build settings
baseurl: /blog
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
excerpt_separator: <!--excerpt_end-->

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
